sudo: required
services:
  - docker

before_install:
  - docker build -t khanhleemtp/docker-react -f Dockerfile.dev .

script:
  - docker run khanhleemtp/docker-react yarn coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react-2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-727229450699"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
